

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class StoreInfo : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the StoreInfo entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public StoreInfo()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public StoreInfo(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.StoreInfo> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.StoreInfo.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreInfo_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreInfo_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.StoreInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.StoreInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string StoreName
        {
            get
            {
                return global::LightSwitchApplication.StoreInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreName);
            }
            set
            {
                global::LightSwitchApplication.StoreInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string StoreUri
        {
            get
            {
                return global::LightSwitchApplication.StoreInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreUri);
            }
            set
            {
                global::LightSwitchApplication.StoreInfo.DetailsClass.SetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreUri, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreUri_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreUri_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StoreUri_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PriceInfo> PriceInfoCollection
        {
            get
            {
                return global::LightSwitchApplication.StoreInfo.DetailsClass.GetValue(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.PriceInfoCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PriceInfo> PriceInfoCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.StoreInfo.DetailsClass.GetQuery(this, global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.PriceInfoCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.StoreInfo,
                global::LightSwitchApplication.StoreInfo.DetailsClass,
                global::LightSwitchApplication.StoreInfo.DetailsClass.IImplementation,
                global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>.Entry
                __StoreInfoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>.Entry(
                    global::LightSwitchApplication.StoreInfo.DetailsClass.__StoreInfo_CreateNew,
                    global::LightSwitchApplication.StoreInfo.DetailsClass.__StoreInfo_Created,
                    global::LightSwitchApplication.StoreInfo.DetailsClass.__StoreInfo_AllowSaveWithErrors);
            private static global::LightSwitchApplication.StoreInfo __StoreInfo_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.StoreInfo> es)
            {
                return new global::LightSwitchApplication.StoreInfo(es);
            }
            private static void __StoreInfo_Created(global::LightSwitchApplication.StoreInfo e)
            {
                e.StoreInfo_Created();
            }
            private static bool __StoreInfo_AllowSaveWithErrors(global::LightSwitchApplication.StoreInfo e)
            {
                bool result = false;
                e.StoreInfo_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string> StoreName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string> StoreUri
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.StoreUri) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo> PriceInfoCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.PriceInfoCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string StoreName { get; set; }
                new string StoreUri { get; set; }
                new global::System.Collections.IEnumerable PriceInfoCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StoreInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int>.Data> c, global::LightSwitchApplication.StoreInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.StoreInfo e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.StoreInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.StoreInfo e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Entry
                    StoreName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Entry(
                        "StoreName",
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_Stub,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_ComputeIsReadOnly,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_Validate,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_GetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_SetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreName_OnValueChanged);
                private static void _StoreName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StoreInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.StoreInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._StoreName, sf);
                }
                private static bool _StoreName_ComputeIsReadOnly(global::LightSwitchApplication.StoreInfo e)
                {
                    bool result = false;
                    e.StoreName_IsReadOnly(ref result);
                    return result;
                }
                private static void _StoreName_Validate(global::LightSwitchApplication.StoreInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StoreName_Validate(r);
                }
                private static string _StoreName_GetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.StoreName;
                }
                private static void _StoreName_SetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.StoreName = v;
                }
                private static void _StoreName_OnValueChanged(global::LightSwitchApplication.StoreInfo e)
                {
                    e.StoreName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Entry
                    StoreUri = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Entry(
                        "StoreUri",
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_Stub,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_ComputeIsReadOnly,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_Validate,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_GetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_SetImplementationValue,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._StoreUri_OnValueChanged);
                private static void _StoreUri_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StoreInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Data> c, global::LightSwitchApplication.StoreInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._StoreUri, sf);
                }
                private static bool _StoreUri_ComputeIsReadOnly(global::LightSwitchApplication.StoreInfo e)
                {
                    bool result = false;
                    e.StoreUri_IsReadOnly(ref result);
                    return result;
                }
                private static void _StoreUri_Validate(global::LightSwitchApplication.StoreInfo e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StoreUri_Validate(r);
                }
                private static string _StoreUri_GetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.StoreUri;
                }
                private static void _StoreUri_SetImplementationValue(global::LightSwitchApplication.StoreInfo.DetailsClass d, string v)
                {
                    d.ImplementationEntity.StoreUri = v;
                }
                private static void _StoreUri_OnValueChanged(global::LightSwitchApplication.StoreInfo e)
                {
                    e.StoreUri_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo>.Entry
                    PriceInfoCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo>.Entry(
                        "PriceInfoCollection",
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._PriceInfoCollection_Stub,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._PriceInfoCollection_GetReferencedEntities,
                        global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties._PriceInfoCollection_GetEntityCollection);
                private static void _PriceInfoCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StoreInfo.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo>.Data> c, global::LightSwitchApplication.StoreInfo.DetailsClass d, object sf)
                {
                    c(d, ref d._PriceInfoCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PriceInfo> _PriceInfoCollection_GetReferencedEntities(global::LightSwitchApplication.StoreInfo.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PriceInfo, global::LightSwitchApplication.PriceInfo.DetailsClass>(global::LightSwitchApplication.StoreInfo.DetailsClass.PropertySetProperties.PriceInfoCollection, ref d._PriceInfoCollection);
                }
                private static global::System.Collections.IEnumerable _PriceInfoCollection_GetEntityCollection(global::LightSwitchApplication.StoreInfo.DetailsClass d)
                {
                    return d.ImplementationEntity.PriceInfoCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Data _StoreName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, string>.Data _StoreUri;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.StoreInfo, global::LightSwitchApplication.StoreInfo.DetailsClass, global::LightSwitchApplication.PriceInfo>.Data _PriceInfoCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
