//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class NeededPartsSetListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private NeededPartsSetListDetail() : base("LightSwitchApplication:NeededPartsSetListDetail")
        {
            global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static NeededPartsSetListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.NeededPartsSetListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSetListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void NeededPartsSet_SelectionChanged();

        partial void NeededPartsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSet_Loaded(bool succeeded);

        partial void NeededBoardsSet_SelectionChanged();

        partial void NeededBoardsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the NeededPartsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.NeededParts> NeededPartsSet
        {
            get
            {
                return global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties.NeededPartsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededPartsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the NeededBoardsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.NeededBoards> NeededBoardsSet
        {
            get
            {
                return global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties.NeededBoardsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the InsertEagleBoms screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InsertEagleBoms()
        {
            this.Details.Methods.InsertEagleBoms.CreateInvocation().Execute();
        }
        partial void InsertEagleBoms_CanExecute(ref bool result);
        partial void InsertEagleBoms_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties.NeededPartsSet;
                var initializeCommandEntry = global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSetProperties.InsertEagleBoms;
                var initializeMethodEntry = global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSetProperties.InsertEagleBoms;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry
                __NeededPartsSetListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeCreated,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeActivated,
                    global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.__NeededPartsSetListDetail_InvokeSaveErrorEvent);
            private static void __NeededPartsSetListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.NeededPartsSetListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.NeededPartsSetListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __NeededPartsSetListDetail_InvokeSavingEvent(global::LightSwitchApplication.NeededPartsSetListDetail s)
            {
                bool handled = false;
                s.NeededPartsSetListDetail_Saving(ref handled);
                return handled;
            }
            private static void __NeededPartsSetListDetail_InvokeSavedEvent(global::LightSwitchApplication.NeededPartsSetListDetail s)
            {
                s.NeededPartsSetListDetail_Saved();
            }
            private static bool __NeededPartsSetListDetail_InvokeClosingEvent(global::LightSwitchApplication.NeededPartsSetListDetail s)
            {
                bool cancel = false;
                s.NeededPartsSetListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __NeededPartsSetListDetail_InvokeCreated(global::LightSwitchApplication.NeededPartsSetListDetail s)
            {
                s.NeededPartsSetListDetail_Created();
            }
            private static void __NeededPartsSetListDetail_InvokeActivated(global::LightSwitchApplication.NeededPartsSetListDetail s)
            {
                s.NeededPartsSetListDetail_Activated();
            }
            private static bool __NeededPartsSetListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.NeededPartsSetListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.NeededPartsSetListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable NeededPartsSetQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.NeededPartsSet,
                    "AvailableParts");
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable NeededBoardsSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.NeededBoardsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts>.Data _NeededPartsSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Data _NeededBoardsSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Data _InsertEagleBomsCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Data _InsertEagleBomsMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts> NeededPartsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts>)base.GetItem(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties.NeededPartsSet);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards> NeededBoardsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>)base.GetItem(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties.NeededBoardsSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass> InsertEagleBoms
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSetProperties.InsertEagleBoms);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass> InsertEagleBoms
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSetProperties.InsertEagleBoms);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts>.Entry
                    NeededPartsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts>.Entry(
                        "NeededPartsSet",
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_Stub,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_Validate,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_CreateQuery,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_SelectionChanged,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_OnCollectionChanged,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededPartsSet_OnLoaded);
                private static void _NeededPartsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededParts>.Data> c, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._NeededPartsSet, sf);
                }
                private static void _NeededPartsSet_Validate(global::LightSwitchApplication.NeededPartsSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.NeededPartsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _NeededPartsSet_CreateQuery(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object[] args)
                {
                    return d.NeededPartsSetQuery();
                }
                private static void _NeededPartsSet_SelectionChanged(global::LightSwitchApplication.NeededPartsSetListDetail s)
                {
                    s.NeededPartsSet_SelectionChanged();
                }
                private static void _NeededPartsSet_OnCollectionChanged(global::LightSwitchApplication.NeededPartsSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.NeededPartsSet_Changed(e);
                }
                private static void _NeededPartsSet_OnLoaded(global::LightSwitchApplication.NeededPartsSetListDetail s, bool succeeded)
                {
                    s.NeededPartsSet_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Entry
                    NeededBoardsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Entry(
                        "NeededBoardsSet",
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_Stub,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_Validate,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_CreateQuery,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_SelectionChanged,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_OnCollectionChanged,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_OnLoaded);
                private static void _NeededBoardsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Data> c, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._NeededBoardsSet, sf);
                }
                private static void _NeededBoardsSet_Validate(global::LightSwitchApplication.NeededPartsSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.NeededBoardsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _NeededBoardsSet_CreateQuery(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object[] args)
                {
                    return d.NeededBoardsSetQuery();
                }
                private static void _NeededBoardsSet_SelectionChanged(global::LightSwitchApplication.NeededPartsSetListDetail s)
                {
                    s.NeededBoardsSet_SelectionChanged();
                }
                private static void _NeededBoardsSet_OnCollectionChanged(global::LightSwitchApplication.NeededPartsSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.NeededBoardsSet_Changed(e);
                }
                private static void _NeededBoardsSet_OnLoaded(global::LightSwitchApplication.NeededPartsSetListDetail s, bool succeeded)
                {
                    s.NeededBoardsSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry
                    InsertEagleBoms = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry(
                        "InsertEagleBoms",
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSetProperties._InsertEagleBoms_Stub,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.CommandSetProperties._InsertEagleBoms_CreateExecutableObject);
                private static void _InsertEagleBoms_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._InsertEagleBomsCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _InsertEagleBoms_CreateExecutableObject(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass)d).Methods.InsertEagleBoms.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry
                    InsertEagleBoms = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Entry(
                        "InsertEagleBoms",
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSetProperties._InsertEagleBoms_Stub,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSetProperties._InsertEagleBoms_CanInvoke,
                        global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass.MethodSetProperties._InsertEagleBoms_InvokeMethod);
                private static void _InsertEagleBoms_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.NeededPartsSetListDetail, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._InsertEagleBomsMethod, sf);
                }
                private static global::System.Exception _InsertEagleBoms_CanInvoke(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.InsertEagleBoms_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _InsertEagleBoms_InvokeMethod(global::LightSwitchApplication.NeededPartsSetListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.InsertEagleBoms_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class AvailablePartsSetListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private AvailablePartsSetListDetail() : base("LightSwitchApplication:AvailablePartsSetListDetail")
        {
            global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static AvailablePartsSetListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.AvailablePartsSetListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSetListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void AvailablePartsSet_SelectionChanged();

        partial void AvailablePartsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSet_Loaded(bool succeeded);

        partial void PriceInfoCollection_SelectionChanged();

        partial void PriceInfoCollection_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PriceInfoCollection_Loaded(bool succeeded);

        /// <summary>
        /// Gets the AvailablePartsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.AvailableParts> AvailablePartsSet
        {
            get
            {
                return global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties.AvailablePartsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvailablePartsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the PriceInfoCollection visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.PriceInfo> PriceInfoCollection
        {
            get
            {
                return global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties.PriceInfoCollection);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PriceInfoCollection_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties.AvailablePartsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>.Entry
                __AvailablePartsSetListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeCreated,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeActivated,
                    global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.__AvailablePartsSetListDetail_InvokeSaveErrorEvent);
            private static void __AvailablePartsSetListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.AvailablePartsSetListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __AvailablePartsSetListDetail_InvokeSavingEvent(global::LightSwitchApplication.AvailablePartsSetListDetail s)
            {
                bool handled = false;
                s.AvailablePartsSetListDetail_Saving(ref handled);
                return handled;
            }
            private static void __AvailablePartsSetListDetail_InvokeSavedEvent(global::LightSwitchApplication.AvailablePartsSetListDetail s)
            {
                s.AvailablePartsSetListDetail_Saved();
            }
            private static bool __AvailablePartsSetListDetail_InvokeClosingEvent(global::LightSwitchApplication.AvailablePartsSetListDetail s)
            {
                bool cancel = false;
                s.AvailablePartsSetListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __AvailablePartsSetListDetail_InvokeCreated(global::LightSwitchApplication.AvailablePartsSetListDetail s)
            {
                s.AvailablePartsSetListDetail_Created();
            }
            private static void __AvailablePartsSetListDetail_InvokeActivated(global::LightSwitchApplication.AvailablePartsSetListDetail s)
            {
                s.AvailablePartsSetListDetail_Activated();
            }
            private static bool __AvailablePartsSetListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.AvailablePartsSetListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable AvailablePartsSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.AvailablePartsSet;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PriceInfoCollectionQuery()
            {
                if (this.Screen.AvailablePartsSet.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PriceInfo> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PriceInfo>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.AvailablePartsSet.SelectedItem.Details.Properties.PriceInfoCollection).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    loader,
                    "StoreInfo");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts>.Data _AvailablePartsSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo>.Data _PriceInfoCollection;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts> AvailablePartsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts>)base.GetItem(global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties.AvailablePartsSet);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo> PriceInfoCollection
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo>)base.GetItem(global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties.PriceInfoCollection);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts>.Entry
                    AvailablePartsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts>.Entry(
                        "AvailablePartsSet",
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_Stub,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_Validate,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_CreateQuery,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_SelectionChanged,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_OnCollectionChanged,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._AvailablePartsSet_OnLoaded);
                private static void _AvailablePartsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.AvailableParts>.Data> c, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._AvailablePartsSet, sf);
                }
                private static void _AvailablePartsSet_Validate(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.AvailablePartsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _AvailablePartsSet_CreateQuery(global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass d, object[] args)
                {
                    return d.AvailablePartsSetQuery();
                }
                private static void _AvailablePartsSet_SelectionChanged(global::LightSwitchApplication.AvailablePartsSetListDetail s)
                {
                    s.AvailablePartsSet_SelectionChanged();
                }
                private static void _AvailablePartsSet_OnCollectionChanged(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.AvailablePartsSet_Changed(e);
                }
                private static void _AvailablePartsSet_OnLoaded(global::LightSwitchApplication.AvailablePartsSetListDetail s, bool succeeded)
                {
                    s.AvailablePartsSet_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo>.Entry
                    PriceInfoCollection = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo>.Entry(
                        "PriceInfoCollection",
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_Stub,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_Validate,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_CreateQuery,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_SelectionChanged,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_OnCollectionChanged,
                        global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass.PropertySetProperties._PriceInfoCollection_OnLoaded);
                private static void _PriceInfoCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.AvailablePartsSetListDetail, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass, global::LightSwitchApplication.PriceInfo>.Data> c, global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PriceInfoCollection, sf);
                }
                private static void _PriceInfoCollection_Validate(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.PriceInfoCollection_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _PriceInfoCollection_CreateQuery(global::LightSwitchApplication.AvailablePartsSetListDetail.DetailsClass d, object[] args)
                {
                    return d.PriceInfoCollectionQuery();
                }
                private static void _PriceInfoCollection_SelectionChanged(global::LightSwitchApplication.AvailablePartsSetListDetail s)
                {
                    s.PriceInfoCollection_SelectionChanged();
                }
                private static void _PriceInfoCollection_OnCollectionChanged(global::LightSwitchApplication.AvailablePartsSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.PriceInfoCollection_Changed(e);
                }
                private static void _PriceInfoCollection_OnLoaded(global::LightSwitchApplication.AvailablePartsSetListDetail s, bool succeeded)
                {
                    s.PriceInfoCollection_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class NeededBoardsSetListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private NeededBoardsSetListDetail() : base("LightSwitchApplication:NeededBoardsSetListDetail")
        {
            global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static NeededBoardsSetListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.NeededBoardsSetListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSetListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void NeededBoardsSet_SelectionChanged();

        partial void NeededBoardsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the NeededBoardsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.NeededBoards> NeededBoardsSet
        {
            get
            {
                return global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties.NeededBoardsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NeededBoardsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties.NeededBoardsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>.Entry
                __NeededBoardsSetListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeCreated,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeActivated,
                    global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.__NeededBoardsSetListDetail_InvokeSaveErrorEvent);
            private static void __NeededBoardsSetListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.NeededBoardsSetListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.NeededBoardsSetListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __NeededBoardsSetListDetail_InvokeSavingEvent(global::LightSwitchApplication.NeededBoardsSetListDetail s)
            {
                bool handled = false;
                s.NeededBoardsSetListDetail_Saving(ref handled);
                return handled;
            }
            private static void __NeededBoardsSetListDetail_InvokeSavedEvent(global::LightSwitchApplication.NeededBoardsSetListDetail s)
            {
                s.NeededBoardsSetListDetail_Saved();
            }
            private static bool __NeededBoardsSetListDetail_InvokeClosingEvent(global::LightSwitchApplication.NeededBoardsSetListDetail s)
            {
                bool cancel = false;
                s.NeededBoardsSetListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __NeededBoardsSetListDetail_InvokeCreated(global::LightSwitchApplication.NeededBoardsSetListDetail s)
            {
                s.NeededBoardsSetListDetail_Created();
            }
            private static void __NeededBoardsSetListDetail_InvokeActivated(global::LightSwitchApplication.NeededBoardsSetListDetail s)
            {
                s.NeededBoardsSetListDetail_Activated();
            }
            private static bool __NeededBoardsSetListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.NeededBoardsSetListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.NeededBoardsSetListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable NeededBoardsSetQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.NeededBoardsSet,
                    "NeededParts");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Data _NeededBoardsSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards> NeededBoardsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>)base.GetItem(global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties.NeededBoardsSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Entry
                    NeededBoardsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Entry(
                        "NeededBoardsSet",
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_Stub,
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_Validate,
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_CreateQuery,
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_SelectionChanged,
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_OnCollectionChanged,
                        global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass.PropertySetProperties._NeededBoardsSet_OnLoaded);
                private static void _NeededBoardsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NeededBoardsSetListDetail, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass, global::LightSwitchApplication.NeededBoards>.Data> c, global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._NeededBoardsSet, sf);
                }
                private static void _NeededBoardsSet_Validate(global::LightSwitchApplication.NeededBoardsSetListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.NeededBoardsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _NeededBoardsSet_CreateQuery(global::LightSwitchApplication.NeededBoardsSetListDetail.DetailsClass d, object[] args)
                {
                    return d.NeededBoardsSetQuery();
                }
                private static void _NeededBoardsSet_SelectionChanged(global::LightSwitchApplication.NeededBoardsSetListDetail s)
                {
                    s.NeededBoardsSet_SelectionChanged();
                }
                private static void _NeededBoardsSet_OnCollectionChanged(global::LightSwitchApplication.NeededBoardsSetListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.NeededBoardsSet_Changed(e);
                }
                private static void _NeededBoardsSet_OnLoaded(global::LightSwitchApplication.NeededBoardsSetListDetail s, bool succeeded)
                {
                    s.NeededBoardsSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
