//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AkidukiDomainServiceData.Implementation
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class AkidukiDomainServiceDataObjectContext : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'AkidukiDomainServiceDataObjectContext' セクションにある接続文字列を使用して新しい AkidukiDomainServiceDataObjectContext オブジェクトを初期化します。
        /// </summary>
        public AkidukiDomainServiceDataObjectContext() : base("name=AkidukiDomainServiceDataObjectContext", "AkidukiDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい AkidukiDomainServiceDataObjectContext オブジェクトを初期化します。
        /// </summary>
        public AkidukiDomainServiceDataObjectContext(string connectionString) : base(connectionString, "AkidukiDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい AkidukiDomainServiceDataObjectContext オブジェクトを初期化します。
        /// </summary>
        public AkidukiDomainServiceDataObjectContext(EntityConnection connection) : base(connection, "AkidukiDomainServiceDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<PartsInfoItem> PartsInfo
        {
            get
            {
                if ((_PartsInfo == null))
                {
                    _PartsInfo = base.CreateObjectSet<PartsInfoItem>("PartsInfo");
                }
                return _PartsInfo;
            }
        }
        private ObjectSet<PartsInfoItem> _PartsInfo;

        #endregion
        #region AddTo メソッド
    
        /// <summary>
        /// PartsInfo EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToPartsInfo(PartsInfoItem partsInfoItem)
        {
            base.AddObject("PartsInfo", partsInfoItem);
        }

        #endregion
    }
    

    #endregion
    
    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkidukiDomainServiceData", Name="PartsInfoItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PartsInfoItem : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい PartsInfoItem オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        public static PartsInfoItem CreatePartsInfoItem(global::System.Int32 id)
        {
            PartsInfoItem partsInfoItem = new PartsInfoItem();
            partsInfoItem.Id = id;
            return partsInfoItem;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LongName
        {
            get
            {
                return _LongName;
            }
            set
            {
                OnLongNameChanging(value);
                ReportPropertyChanging("LongName");
                _LongName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LongName");
                OnLongNameChanged();
            }
        }
        private global::System.String _LongName;
        partial void OnLongNameChanging(global::System.String value);
        partial void OnLongNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartsImageUri
        {
            get
            {
                return _PartsImageUri;
            }
            set
            {
                OnPartsImageUriChanging(value);
                ReportPropertyChanging("PartsImageUri");
                _PartsImageUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PartsImageUri");
                OnPartsImageUriChanged();
            }
        }
        private global::System.String _PartsImageUri;
        partial void OnPartsImageUriChanging(global::System.String value);
        partial void OnPartsImageUriChanged();

        #endregion
    
    }

    #endregion
    
}
